//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarbonFootprint.user
{


    public partial class ContactAF
    {

        /// <summary>
        /// phUserLinks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phUserLinks;

        /// <summary>
        /// phAdminLinks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminLinks;

        /// <summary>
        /// txtContactName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactName;

        /// <summary>
        /// txtContactEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactEmail;

        /// <summary>
        /// txtContactSubject control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactSubject;

        /// <summary>
        /// txtContactMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactMessage;

        /// <summary>
        /// btnContactSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnContactSubmit;

        /// <summary>
        /// lblContactStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblContactStatus;

        /// <summary>
        /// txtFeedbackSubject control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFeedbackSubject;

        /// <summary>
        /// txtFeedbackMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFeedbackMessage;

        /// <summary>
        /// ddlFeedbackType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFeedbackType;

        /// <summary>
        /// hdnRating control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnRating;

        /// <summary>
        /// btnFeedbackSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnFeedbackSubmit;

        /// <summary>
        /// lblFeedbackStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFeedbackStatus;
    }
}
