//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarbonFootprint.user
{


    public partial class ProfileHR
    {

        /// <summary>
        /// phUserLinks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phUserLinks;

        /// <summary>
        /// phAdminLinks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminLinks;

        /// <summary>
        /// lblProfileName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProfileName;

        /// <summary>
        /// lblProfileEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProfileEmail;

        /// <summary>
        /// lblMemberSince control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMemberSince;

        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// txtLocation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLocation;

        /// <summary>
        /// btnSaveProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;

        /// <summary>
        /// lblProfileStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProfileStatus;

        /// <summary>
        /// rptHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptHistory;

        /// <summary>
        /// lblHistoryEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblHistoryEmpty;

        /// <summary>
        /// rptRecommendations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRecommendations;

        /// <summary>
        /// lblRecEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRecEmpty;
    }
}
